contexts:
- data:
    output_dir: launchpad-processed
    services_dir: launchpad-services
    templates_dir: launchpad-templates
  name: launchpad
  namespace: launchpad-production
current: launchpad
