contexts:
- data:
    output_dir: launchpad-processed
    services_dir: launchpad-services
    templates_dir: launchpad-templates
  name: launchpad
  environments:
    production:
      namespace: launchpad-production
    staging:
      namespace: launchpad-preview
current: launchpad
